import os
from datetime import timedelta


class SubtitleGenerator:
    def __init__(self):
        self.default_style = {
            "font": "Arial",
            "size": 24,
            "color": "&H00FFFFFF",
            "outline_color": "&H00000000",
            "outline": 2,
            "shadow": 1,
            "bold": False,
            "italic": False,
            "underline": False,
            "alignment": 2,
            "margin_v": 30,
            "encoding": 1
        }

    def generate_srt(self, segments: list[dict], output_path: str,
                     use_translated: bool = True) -> str:
        with open(output_path, "w", encoding="utf-8") as f:
            for i, segment in enumerate(segments, 1):
                start = self._format_time_srt(segment["start"])
                end = self._format_time_srt(segment["end"])

                text = segment.get("translated", "") if use_translated else segment["text"]
                if not text:
                    text = segment["text"]

                f.write(f"{i}\n")
                f.write(f"{start} --> {end}\n")
                f.write(f"{text}\n\n")

        return output_path

    def generate_both_srt(self, segments: list[dict], base_path: str,
                          original_lang: str = "orijinal",
                          translated_lang: str = "cevirilmis") -> tuple[str, str]:
        original_path = base_path.replace(".srt", f"_{original_lang}.srt")
        translated_path = base_path.replace(".srt", f"_{translated_lang}.srt")

        self.generate_srt(segments, original_path, use_translated=False)
        self.generate_srt(segments, translated_path, use_translated=True)

        return original_path, translated_path

    def generate_both_ass(self, segments: list[dict], base_path: str,
                          style_config: dict = None,
                          original_lang: str = "orijinal",
                          translated_lang: str = "cevirilmis") -> tuple[str, str]:
        original_path = base_path.replace(".ass", f"_{original_lang}.ass")
        translated_path = base_path.replace(".ass", f"_{translated_lang}.ass")

        self.generate_ass(segments, original_path, style_config, use_translated=False)
        self.generate_ass(segments, translated_path, style_config, use_translated=True)

        return original_path, translated_path

    def generate_ass(self, segments: list[dict], output_path: str,
                     style_config: dict = None, use_translated: bool = True) -> str:
        style = self.default_style.copy()
        if style_config:
            style.update(style_config)

        header = self._generate_ass_header(style)
        events = self._generate_ass_events(segments, style, use_translated)

        with open(output_path, "w", encoding="utf-8-sig") as f:
            f.write(header)
            f.write(events)

        return output_path

    def _generate_ass_header(self, style: dict) -> str:
        font_name = style.get("font", "Arial")
        font_size = style.get("size", 24)
        primary_color = self._convert_color_to_ass(style.get("color", "#FFFFFF"))
        outline_color = self._convert_color_to_ass(style.get("outline_color", "#000000"))
        outline = style.get("outline", 2)
        shadow = style.get("shadow", 1)
        bold = -1 if style.get("bold", False) else 0
        italic = -1 if style.get("italic", False) else 0
        underline = -1 if style.get("underline", False) else 0
        alignment = style.get("alignment", 2)
        margin_v = style.get("margin_v", 30)

        return f"""[Script Info]
; Script generated by AltyaziApp
Title: AltyaziApp
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.709
PlayResX: 1920
PlayResY: 1080

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,{font_name},{font_size},{primary_color},&H000000FF,{outline_color},&H80000000,{bold},{italic},{underline},0,100,100,0,0,1,{outline},{shadow},{alignment},10,10,{margin_v},1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""

    def _convert_color_to_ass(self, hex_color: str) -> str:
        hex_color = hex_color.lstrip('#')
        if len(hex_color) == 6:
            r = int(hex_color[0:2], 16)
            g = int(hex_color[2:4], 16)
            b = int(hex_color[4:6], 16)
            return f"&H00{b:02X}{g:02X}{r:02X}"
        return "&H00FFFFFF"

    def _generate_ass_events(self, segments: list[dict], style: dict,
                             use_translated: bool) -> str:
        events = []
        font_size = style.get("size", 24)
        max_chars = max(20, int(1920 / (font_size * 0.55)))

        for i, segment in enumerate(segments):
            text = segment.get("translated", "") if use_translated else segment["text"]
            if not text:
                text = segment["text"]

            start = segment["start"]
            end = self._calculate_end_time(segment, i, segments, use_translated)

            start_str = self._format_time_ass(start)
            end_str = self._format_time_ass(end)

            text = self._wrap_text(text, max_chars)
            text = text.replace("\n", "\\N")

            events.append(
                f"Dialogue: 0,{start_str},{end_str},Default,,0,0,0,,{text}"
            )

        return "\n".join(events)

    def _calculate_end_time(self, segment: dict, index: int,
                            segments: list[dict], use_translated: bool) -> float:
        start = segment["start"]
        text = segment.get("translated", "") if use_translated else segment.get("text", "")
        if not text:
            text = segment.get("text", "")

        char_count = len(text)
        word_count = len(text.split())

        # Okuma hızı: ~15 karakter/saniye, minimum 1.5sn, maksimum 7sn
        chars_per_sec = 15
        min_duration = 1.5
        max_duration = 7.0

        ideal_duration = max(min_duration, char_count / chars_per_sec)
        duration = min(ideal_duration, max_duration)

        # Bir sonraki altyazıyla çakışmayı önle
        if index + 1 < len(segments):
            next_start = segments[index + 1]["start"]
            end = min(start + duration, next_start - 0.05)
        else:
            end = start + duration

        return max(end, start + min_duration)

    def _wrap_text(self, text: str, max_chars: int) -> str:
        if len(text) <= max_chars:
            return text

        words = text.split()
        lines = []
        current_line = ""
        for word in words:
            test = f"{current_line} {word}".strip() if current_line else word
            if len(test) <= max_chars:
                current_line = test
            else:
                if current_line:
                    lines.append(current_line)
                current_line = word
        if current_line:
            lines.append(current_line)

        if len(lines) > 2:
            mid = len(text) // 2
            left = text[:mid].rsplit(" ", 1)[0] if " " in text[:mid] else text[:mid]
            right = text[mid:].lstrip() if " " in text[mid:] else text[mid:]
            return f"{left}\n{right}"

        return "\n".join(lines)

    def _format_time_srt(self, seconds: float) -> str:
        td = timedelta(seconds=seconds)
        hours = int(td.total_seconds() // 3600)
        minutes = int((td.total_seconds() % 3600) // 60)
        secs = int(td.total_seconds() % 60)
        millis = int((td.total_seconds() % 1) * 1000)

        return f"{hours:02d}:{minutes:02d}:{secs:02d},{millis:03d}"

    def _format_time_ass(self, seconds: float) -> str:
        td = timedelta(seconds=seconds)
        hours = int(td.total_seconds() // 3600)
        minutes = int((td.total_seconds() % 3600) // 60)
        secs = int(td.total_seconds() % 60)
        millis = int((td.total_seconds() % 1) * 100)

        return f"{hours}:{minutes:02d}:{secs:02d}.{millis:02d}"

    def parse_srt(self, srt_path: str) -> list[dict]:
        segments = []
        with open(srt_path, "r", encoding="utf-8") as f:
            content = f.read()

        blocks = content.strip().split("\n\n")
        for block in blocks:
            lines = block.strip().split("\n")
            if len(lines) >= 3:
                time_line = lines[1]
                text = " ".join(lines[2:])

                start_str, end_str = time_line.split(" --> ")
                start = self._parse_srt_time(start_str)
                end = self._parse_srt_time(end_str)

                segments.append({
                    "start": start,
                    "end": end,
                    "text": text,
                    "translated": text
                })

        return segments

    def _parse_srt_time(self, time_str: str) -> float:
        time_str = time_str.strip()
        parts = time_str.replace(",", ".").split(":")

        hours = int(parts[0])
        minutes = int(parts[1])
        seconds = float(parts[2])

        return hours * 3600 + minutes * 60 + seconds
